# Generated by Django 3.1.2 on 2021-01-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_no',
            field=models.CharField(default=0, max_length=31),
            preserve_default=False,
        ),
    ]
