# Generated by Django 3.1.2 on 2021-01-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0002_auto_20210130_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
